# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/toolformer',
                'doc_host': 'https://qcname.github.io',
                'git_url': 'https://github.com/qcname/toolformer',
                'lib_path': 'toolformer'},
  'syms': {'toolformer.core': {'toolformer.core.foo': ('core.html#foo', 'toolformer/core.py')}}}
