"""core.py description"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo', 'mse']

# %% ../nbs/00_core.ipynb 4
def say_hello(name:str # 名称
            ) -> str: # 返回字符串
    return f"Hello, {name}!"

# %% ../nbs/00_core.ipynb 5
def foo(a,b): return a+2*b
foo(1,4)

# %% ../nbs/00_core.ipynb 10
def mse(y_true, y_pred):
    r"""
    计算均方误差：
    $$ 
    \text{MSE} = \frac{1}{n}\sum_{i=1}^n (y_i - \hat{y}_i)^2 
    $$
    """
    return ((y_true - y_pred) ** 2).mean()
