"""test"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_usage.ipynb.

# %% auto 0
__all__ = ['o', 'foo1', 'HelloSayer']

# %% ../nbs/01_usage.ipynb 4
def foo1(name):say_hello(name)
foo1("ni")

# %% ../nbs/01_usage.ipynb 5
class HelloSayer:
    "`say_hello` to someone" 
    def __init__(self,to):self.to=to
    def say(self):
        "do the saying" 
        return say_hello(self.to)
o=HelloSayer('qian')
o.say()
