# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_utils.ipynb.

# %% auto 0
__all__ = ['yaml2dict', 'extract_api_content', 'extract_api_syntax', 'extract_api_name']

# %% ../nbs/00_utils.ipynb 2
import yaml
import re
from typing import Optional

# %% ../nbs/00_utils.ipynb 3
def yaml2dict(file_path):
    with open(file_path,"r") as file:
        data=yaml.safe_load(file)
    return data

# %% ../nbs/00_utils.ipynb 4
def extract_api_content(text:str,api_name:str)->str:
    """从给定的文本中抽取出api请求"""
    start_tag=f"{api_name}("
    end_tag=")"
    start_idx=text.find(start_tag)
    if start_idx==-1:
        return None
    start_idx+=len(start_tag)
    end_idx=text.find(end_tag,start_idx)
    if end_idx==-1:
        return None
    return text[start_idx:end_idx]

# %% ../nbs/00_utils.ipynb 5
def extract_api_syntax(text:str,api_name:str)->str:
    """抽取语法"""
    pattern = r"\[{}\(.*?\)\]".format(api_name)
    matches = re.findall(pattern, text)
    return matches

# %% ../nbs/00_utils.ipynb 6
def extract_api_name(text:str,is_end_token:bool=True)->Optional[str]:
    if is_end_token:
        pattern=r'\[(\w+)\(.+\]\s?'
    else:
        pattern=r'\[(\w+)\(.+\s?'
    match=re.search(pattern,text)
    if match:
        return match.group(1)
    else:
        return None
